#writen by Brinkley Sharpe, edited by Max M. Owens
#############################
## Load required libraries ##                                                    
#############################
library(tidyverse)
library(readxl)
library(nlme)
library(lme4)
library(MuMIn)

#####################
## Set working directory##
#set working directory
setwd("/home/max/Documents/hilo/")

######################
## Define variables ##                                                    
######################
# Raw NEO-FFI items
neo_raw <- c('NEORAW_01', 'NEORAW_02', 'NEORAW_03', 'NEORAW_04', 'NEORAW_05',
             'NEORAW_06', 'NEORAW_07', 'NEORAW_08', 'NEORAW_09', 'NEORAW_10', 
             'NEORAW_11', 'NEORAW_12', 'NEORAW_13', 'NEORAW_14', 'NEORAW_15', 
             'NEORAW_16', 'NEORAW_17', 'NEORAW_18', 'NEORAW_19', 'NEORAW_20', 
             'NEORAW_21', 'NEORAW_22', 'NEORAW_23', 'NEORAW_24', 'NEORAW_25', 
             'NEORAW_26', 'NEORAW_27', 'NEORAW_28', 'NEORAW_29', 'NEORAW_30', 
             'NEORAW_31', 'NEORAW_32', 'NEORAW_33', 'NEORAW_34', 'NEORAW_35', 
             'NEORAW_36', 'NEORAW_37', 'NEORAW_38', 'NEORAW_39', 'NEORAW_40',
             'NEORAW_41', 'NEORAW_42', 'NEORAW_43', 'NEORAW_44', 'NEORAW_45', 
             'NEORAW_46', 'NEORAW_47', 'NEORAW_48', 'NEORAW_49', 'NEORAW_50', 
             'NEORAW_51', 'NEORAW_52', 'NEORAW_53', 'NEORAW_54', 'NEORAW_55',
             'NEORAW_56', 'NEORAW_57', 'NEORAW_58', 'NEORAW_59', 'NEORAW_60')
# NEO-FFI metatraits
metatraits <- c('neoStability', 'neoPlasticity')
# NEO-FFI traits
traits <- c('neoN', 'neoE', 'neoO', 'neoA', 'neoC')
# NEO-FFI facets
facets <- c('neoAnxiety', 'neoDepression', 'neoSelfConsciousness',
            'neoVulnerability', 'neoGregariousness', 'neoActivityLevel', 
            'neoCheerfulness', 'neoArtisticInterests', 'neoAdventurousness', 
            'neoIntellect', 'neoLiberalism', 'neoTrust', 'neoAltruism', 
            'neoCooperation', 'neoOrderliness', 'neoDutifulness', 
            'neoAchievementStriving', 'neoSelfDiscipline')
# All personality variables
personality <- c(metatraits, traits, facets, neo_raw)
personality.list <- list('Meta-Trait' = metatraits, 
                         'Trait' = traits, 
                         'Facet' = facets, 
                         'Item' = neo_raw)
# Omnibus index variables
omnibus <- c('FS_BrainSeg_Vol', 'FS_Total_GM_Vol', 'FS_Tot_WM_Vol', 
             'FS_TotCort_GM_Vol', 'FS_SubCort_GM_Vol', 'WhiteSurfArea_area', 
             'MeanThickness_thickness')
# Subcortical region variables
subcortical <- c('FS_L_AccumbensArea_Vol', 'FS_L_Amygdala_Vol', 
                 'FS_L_Caudate_Vol', 'FS_L_Hippo_Vol', 'FS_L_Pallidum_Vol', 
                 'FS_L_Putamen_Vol', 'FS_L_ThalamusProper_Vol', 
                 'FS_L_VentDC_Vol', 'FS_R_AccumbensArea_Vol', 
                 'FS_R_Amygdala_Vol', 'FS_R_Caudate_Vol', 'FS_R_Hippo_Vol',
                 'FS_R_Pallidum_Vol', 'FS_R_Putamen_Vol', 
                 'FS_R_ThalamusProper_Vol', 'FS_R_VentDC_Vol',
                 'FS_L_Cerebellum_Cort_Vol', 'FS_R_Cerebellum_Cort_Vol')
# Desikan cortical thickness variables
desikanCT<- c('FS_L_Bankssts_Thck', 'FS_L_Caudalanteriorcingulate_Thck',
              'FS_L_Caudalmiddlefrontal_Thck', 'FS_L_Cuneus_Thck',
              'FS_L_Entorhinal_Thck', 'FS_L_Frontalpole_Thck', 
              'FS_L_Fusiform_Thck', 'FS_L_Inferiorparietal_Thck', 
              'FS_L_Inferiortemporal_Thck', 'FS_L_Insula_Thck',
              'FS_L_Isthmuscingulate_Thck', 'FS_L_Lateraloccipital_Thck', 
              'FS_L_Lateralorbitofrontal_Thck', 'FS_L_Lingual_Thck',
              'FS_L_Medialorbitofrontal_Thck', 'FS_L_Middletemporal_Thck', 
              'FS_L_Paracentral_Thck', 'FS_L_Parahippocampal_Thck', 
              'FS_L_Parsopercularis_Thck', 'FS_L_Parsorbitalis_Thck',
              'FS_L_Parstriangularis_Thck', 'FS_L_Pericalcarine_Thck',
              'FS_L_Postcentral_Thck', 'FS_L_Posteriorcingulate_Thck',
              'FS_L_Precentral_Thck', 'FS_L_Precuneus_Thck',
              'FS_L_Rostralanteriorcingulate_Thck',
              'FS_L_Rostralmiddlefrontal_Thck', 'FS_L_Superiorfrontal_Thck', 
              'FS_L_Superiorparietal_Thck', 'FS_L_Superiortemporal_Thck', 
              'FS_L_Supramarginal_Thck', 'FS_L_Temporalpole_Thck', 
              'FS_L_Transversetemporal_Thck', 'FS_R_Bankssts_Thck', 
              'FS_R_Caudalanteriorcingulate_Thck', 
              'FS_R_Caudalmiddlefrontal_Thck', 'FS_R_Cuneus_Thck',
              'FS_R_Entorhinal_Thck', 'FS_R_Frontalpole_Thck',
              'FS_R_Fusiform_Thck', 'FS_R_Inferiorparietal_Thck', 
              'FS_R_Inferiortemporal_Thck', 'FS_R_Insula_Thck',
              'FS_R_Isthmuscingulate_Thck', 'FS_R_Lateraloccipital_Thck', 
              'FS_R_Lateralorbitofrontal_Thck', 'FS_R_Lingual_Thck',
              'FS_R_Medialorbitofrontal_Thck', 'FS_R_Middletemporal_Thck', 
              'FS_R_Paracentral_Thck', 'FS_R_Parahippocampal_Thck', 
              'FS_R_Parsopercularis_Thck', 'FS_R_Parsorbitalis_Thck',
              'FS_R_Parstriangularis_Thck', 'FS_R_Pericalcarine_Thck',
              'FS_R_Postcentral_Thck', 'FS_R_Posteriorcingulate_Thck',
              'FS_R_Precentral_Thck', 'FS_R_Precuneus_Thck', 
              'FS_R_Rostralanteriorcingulate_Thck', 
              'FS_R_Rostralmiddlefrontal_Thck', 'FS_R_Superiorfrontal_Thck',
              'FS_R_Superiorparietal_Thck', 'FS_R_Superiortemporal_Thck', 
              'FS_R_Supramarginal_Thck', 'FS_R_Temporalpole_Thck', 
              'FS_R_Transversetemporal_Thck')
# Desikan cortial area variables
desikanCA <- c('FS_L_Bankssts_Area', 'FS_L_Caudalanteriorcingulate_Area',
               'FS_L_Caudalmiddlefrontal_Area', 'FS_L_Cuneus_Area', 
               'FS_L_Entorhinal_Area', 'FS_L_Frontalpole_Area',
               'FS_L_Fusiform_Area', 'FS_L_Inferiorparietal_Area',
               'FS_L_Inferiortemporal_Area', 'FS_L_Insula_Area',
               'FS_L_Isthmuscingulate_Area', 'FS_L_Lateraloccipital_Area',
               'FS_L_Lateralorbitofrontal_Area', 'FS_L_Lingual_Area',
               'FS_L_Medialorbitofrontal_Area', 'FS_L_Middletemporal_Area',
               'FS_L_Paracentral_Area', 'FS_L_Parahippocampal_Area', 
               'FS_L_Parsopercularis_Area', 'FS_L_Parsorbitalis_Area',
               'FS_L_Parstriangularis_Area', 'FS_L_Pericalcarine_Area',
               'FS_L_Postcentral_Area', 'FS_L_Posteriorcingulate_Area',
               'FS_L_Precentral_Area', 'FS_L_Precuneus_Area',
               'FS_L_Rostralanteriorcingulate_Area', 
               'FS_L_Rostralmiddlefrontal_Area', 'FS_L_Superiorfrontal_Area',
               'FS_L_Superiorparietal_Area', 'FS_L_Superiortemporal_Area', 
               'FS_L_Supramarginal_Area', 'FS_L_Temporalpole_Area',
               'FS_L_Transversetemporal_Area', 'FS_R_Bankssts_Area',
               'FS_R_Caudalanteriorcingulate_Area',
               'FS_R_Caudalmiddlefrontal_Area', 'FS_R_Cuneus_Area',
               'FS_R_Entorhinal_Area', 'FS_R_Frontalpole_Area',
               'FS_R_Fusiform_Area', 'FS_R_Inferiorparietal_Area', 
               'FS_R_Inferiortemporal_Area', 'FS_R_Insula_Area',
               'FS_R_Isthmuscingulate_Area', 'FS_R_Lateraloccipital_Area', 
               'FS_R_Lateralorbitofrontal_Area', 'FS_R_Lingual_Area',
               'FS_R_Medialorbitofrontal_Area', 'FS_R_Middletemporal_Area',
               'FS_R_Paracentral_Area', 'FS_R_Parahippocampal_Area', 
               'FS_R_Parsopercularis_Area', 'FS_R_Parsorbitalis_Area', 
               'FS_R_Parstriangularis_Area', 'FS_R_Pericalcarine_Area', 
               'FS_R_Postcentral_Area', 'FS_R_Posteriorcingulate_Area', 
               'FS_R_Precentral_Area', 'FS_R_Precuneus_Area',
               'FS_R_Rostralanteriorcingulate_Area', 
               'FS_R_Rostralmiddlefrontal_Area', 'FS_R_Superiorfrontal_Area',
               'FS_R_Superiorparietal_Area', 'FS_R_Superiortemporal_Area',
               'FS_R_Supramarginal_Area', 'FS_R_Temporalpole_Area',
               'FS_R_Transversetemporal_Area')
# Destrieux cortical thickness variables
destrieuxCT <- c('rh_G_and_S_frontomargin_thickness',
                 'rh_G_and_S_occipital_inf_thickness',
                 'rh_G_and_S_paracentral_thickness',
                 'rh_G_and_S_subcentral_thickness',
                 'rh_G_and_S_transv_frontopol_thickness',
                 'rh_G_and_S_cingul-Ant_thickness',
                 'rh_G_and_S_cingul-Mid-Ant_thickness',
                 'rh_G_and_S_cingul-Mid-Post_thickness', 
                 'rh_G_cingul-Post-dorsal_thickness',
                 'rh_G_cingul-Post-ventral_thickness', 'rh_G_cuneus_thickness', 
                 'rh_G_front_inf-Opercular_thickness',
                 'rh_G_front_inf-Orbital_thickness', 
                 'rh_G_front_inf-Triangul_thickness',
                 'rh_G_front_middle_thickness', 'rh_G_front_sup_thickness',
                 'rh_G_Ins_lg_and_S_cent_ins_thickness',
                 'rh_G_insular_short_thickness', 
                 'rh_G_occipital_middle_thickness',
                 'rh_G_occipital_sup_thickness',
                 'rh_G_oc-temp_lat-fusifor_thickness',
                 'rh_G_oc-temp_med-Lingual_thickness',
                 'rh_G_oc-temp_med-Parahip_thickness', 'rh_G_orbital_thickness',
                 'rh_G_pariet_inf-Angular_thickness',
                 'rh_G_pariet_inf-Supramar_thickness',
                 'rh_G_parietal_sup_thickness', 'rh_G_postcentral_thickness',
                 'rh_G_precentral_thickness', 'rh_G_precuneus_thickness',
                 'rh_G_rectus_thickness', 'rh_G_subcallosal_thickness',
                 'rh_G_temp_sup-G_T_transv_thickness',
                 'rh_G_temp_sup-Lateral_thickness',
                 'rh_G_temp_sup-Plan_polar_thickness',
                 'rh_G_temp_sup-Plan_tempo_thickness', 
                 'rh_G_temporal_inf_thickness', 
                 'rh_G_temporal_middle_thickness',
                 'rh_Lat_Fis-ant-Horizont_thickness',
                 'rh_Lat_Fis-ant-Vertical_thickness', 
                 'rh_Lat_Fis-post_thickness', 'rh_Pole_occipital_thickness',
                 'rh_Pole_temporal_thickness', 'rh_S_calcarine_thickness',
                 'rh_S_central_thickness', 'rh_S_cingul-Marginalis_thickness',
                 'rh_S_circular_insula_ant_thickness',
                 'rh_S_circular_insula_inf_thickness',	
                 'rh_S_circular_insula_sup_thickness', 
                 'rh_S_collat_transv_ant_thickness',
                 'rh_S_collat_transv_post_thickness', 
                 'rh_S_front_inf_thickness', 'rh_S_front_middle_thickness',
                 'rh_S_front_sup_thickness', 
                 'rh_S_interm_prim-Jensen_thickness',
                 'rh_S_intrapariet_and_P_trans_thickness',
                 'rh_S_oc_middle_and_Lunatus_thickness',
                 'rh_S_oc_sup_and_transversal_thickness',
                 'rh_S_occipital_ant_thickness',
                 'rh_S_oc-temp_lat_thickness',
                 'rh_S_oc-temp_med_and_Lingual_thickness',
                 'rh_S_orbital_lateral_thickness',
                 'rh_S_orbital_med-olfact_thickness',
                 'rh_S_orbital-H_Shaped_thickness',
                 'rh_S_parieto_occipital_thickness',	
                 'rh_S_pericallosal_thickness',
                 'rh_S_postcentral_thickness',
                 'rh_S_precentral-inf-part_thickness',
                 'rh_S_precentral-sup-part_thickness',
                 'rh_S_suborbital_thickness', 'rh_S_subparietal_thickness',
                 'rh_S_temporal_inf_thickness', 'rh_S_temporal_sup_thickness',
                 'rh_S_temporal_transverse_thickness', 
                 'lh_G_and_S_frontomargin_thickness', 
                 'lh_G_and_S_occipital_inf_thickness',
                 'lh_G_and_S_paracentral_thickness',
                 'lh_G_and_S_subcentral_thickness',
                 'lh_G_and_S_transv_frontopol_thickness',
                 'lh_G_and_S_cingul-Ant_thickness',
                 'lh_G_and_S_cingul-Mid-Ant_thickness',
                 'lh_G_and_S_cingul-Mid-Post_thickness',
                 'lh_G_cingul-Post-dorsal_thickness',
                 'lh_G_cingul-Post-ventral_thickness', 'lh_G_cuneus_thickness', 
                 'lh_G_front_inf-Opercular_thickness',
                 'lh_G_front_inf-Orbital_thickness',
                 'lh_G_front_inf-Triangul_thickness',
                 'lh_G_front_middle_thickness',	'lh_G_front_sup_thickness',
                 'lh_G_Ins_lg_and_S_cent_ins_thickness',
                 'lh_G_insular_short_thickness',
                 'lh_G_occipital_middle_thickness',
                 'lh_G_occipital_sup_thickness',
                 'lh_G_oc-temp_lat-fusifor_thickness',
                 'lh_G_oc-temp_med-Lingual_thickness',
                 'lh_G_oc-temp_med-Parahip_thickness', 'lh_G_orbital_thickness',
                 'lh_G_pariet_inf-Angular_thickness',
                 'lh_G_pariet_inf-Supramar_thickness',
                 'lh_G_parietal_sup_thickness', 'lh_G_postcentral_thickness',
                 'lh_G_precentral_thickness', 'lh_G_precuneus_thickness',
                 'lh_G_rectus_thickness', 'lh_G_subcallosal_thickness',
                 'lh_G_temp_sup-G_T_transv_thickness',
                 'lh_G_temp_sup-Lateral_thickness',
                 'lh_G_temp_sup-Plan_polar_thickness',
                 'lh_G_temp_sup-Plan_tempo_thickness',
                 'lh_G_temporal_inf_thickness',
                 'lh_G_temporal_middle_thickness',
                 'lh_Lat_Fis-ant-Horizont_thickness',
                 'lh_Lat_Fis-ant-Vertical_thickness', 
                 'lh_Lat_Fis-post_thickness', 'lh_Pole_occipital_thickness',
                 'lh_Pole_temporal_thickness', 'lh_S_calcarine_thickness',
                 'lh_S_central_thickness', 'lh_S_cingul-Marginalis_thickness',
                 'lh_S_circular_insula_ant_thickness',
                 'lh_S_circular_insula_inf_thickness',	
                 'lh_S_circular_insula_sup_thickness',
                 'lh_S_collat_transv_ant_thickness',
                 'lh_S_collat_transv_post_thickness', 
                 'lh_S_front_inf_thickness', 'lh_S_front_middle_thickness',
                 'lh_S_front_sup_thickness', 
                 'lh_S_interm_prim-Jensen_thickness',
                 'lh_S_intrapariet_and_P_trans_thickness',
                 'lh_S_oc_middle_and_Lunatus_thickness',
                 'lh_S_oc_sup_and_transversal_thickness',
                 'lh_S_occipital_ant_thickness', 'lh_S_oc-temp_lat_thickness',
                 'lh_S_oc-temp_med_and_Lingual_thickness',
                 'lh_S_orbital_lateral_thickness',
                 'lh_S_orbital_med-olfact_thickness',
                 'lh_S_orbital-H_Shaped_thickness',
                 'lh_S_parieto_occipital_thickness',
                 'lh_S_pericallosal_thickness', 'lh_S_postcentral_thickness',
                 'lh_S_precentral-inf-part_thickness',
                 'lh_S_precentral-sup-part_thickness',
                 'lh_S_suborbital_thickness', 'lh_S_subparietal_thickness',
                 'lh_S_temporal_inf_thickness', 'lh_S_temporal_sup_thickness',
                 'lh_S_temporal_transverse_thickness')
# Destrieux cortical area variables
destrieuxCA <- c('rh_G_and_S_frontomargin_area', 
                 'rh_G_and_S_occipital_inf_area', 'rh_G_and_S_paracentral_area',	
                 'rh_G_and_S_subcentral_area',
                 'rh_G_and_S_transv_frontopol_area',
                 'rh_G_and_S_cingul-Ant_area', 'rh_G_and_S_cingul-Mid-Ant_area',
                 'rh_G_and_S_cingul-Mid-Post_area',	
                 'rh_G_cingul-Post-dorsal_area', 
                 'rh_G_cingul-Post-ventral_area',	'rh_G_cuneus_area',	
                 'rh_G_front_inf-Opercular_area',	'rh_G_front_inf-Orbital_area',	
                 'rh_G_front_inf-Triangul_area', 'rh_G_front_middle_area',
                 'rh_G_front_sup_area', 'rh_G_Ins_lg_and_S_cent_ins_area',
                 'rh_G_insular_short_area',	'rh_G_occipital_middle_area',
                 'rh_G_occipital_sup_area',	'rh_G_oc-temp_lat-fusifor_area',
                 'rh_G_oc-temp_med-Lingual_area',	
                 'rh_G_oc-temp_med-Parahip_area',	'rh_G_orbital_area',
                 'rh_G_pariet_inf-Angular_area',	
                 'rh_G_pariet_inf-Supramar_area',	'rh_G_parietal_sup_area',
                 'rh_G_postcentral_area',	'rh_G_precentral_area',
                 'rh_G_precuneus_area', 'rh_G_rectus_area', 
                 'rh_G_subcallosal_area',	'rh_G_temp_sup-G_T_transv_area',
                 'rh_G_temp_sup-Lateral_area', 'rh_G_temp_sup-Plan_polar_area',	
                 'rh_G_temp_sup-Plan_tempo_area',	'rh_G_temporal_inf_area',
                 'rh_G_temporal_middle_area',	'rh_Lat_Fis-ant-Horizont_area',	
                 'rh_Lat_Fis-ant-Vertical_area', 'rh_Lat_Fis-post_area',
                 'rh_Pole_occipital_area', 'rh_Pole_temporal_area',
                 'rh_S_calcarine_area',	'rh_S_central_area', 
                 'rh_S_cingul-Marginalis_area',	'rh_S_circular_insula_ant_area',	
                 'rh_S_circular_insula_inf_area',	
                 'rh_S_circular_insula_sup_area',	'rh_S_collat_transv_ant_area',	
                 'rh_S_collat_transv_post_area', 'rh_S_front_inf_area',	
                 'rh_S_front_middle_area', 'rh_S_front_sup_area',
                 'rh_S_interm_prim-Jensen_area',
                 'rh_S_intrapariet_and_P_trans_area',
                 'rh_S_oc_middle_and_Lunatus_area', 
                 'rh_S_oc_sup_and_transversal_area', 'rh_S_occipital_ant_area',
                 'rh_S_oc-temp_lat_area', 'rh_S_oc-temp_med_and_Lingual_area',	
                 'rh_S_orbital_lateral_area',	'rh_S_orbital_med-olfact_area',
                 'rh_S_orbital-H_Shaped_area', 'rh_S_parieto_occipital_area',	
                 'rh_S_pericallosal_area', 'rh_S_postcentral_area',	
                 'rh_S_precentral-inf-part_area',	
                 'rh_S_precentral-sup-part_area',	'rh_S_suborbital_area',
                 'rh_S_subparietal_area',	'rh_S_temporal_inf_area',	
                 'rh_S_temporal_sup_area', 'rh_S_temporal_transverse_area',
                 'lh_G_and_S_frontomargin_area',
                 'lh_G_and_S_occipital_inf_area', 'lh_G_and_S_paracentral_area',	
                 'lh_G_and_S_subcentral_area',
                 'lh_G_and_S_transv_frontopol_area',
                 'lh_G_and_S_cingul-Ant_area', 'lh_G_and_S_cingul-Mid-Ant_area',
                 'lh_G_and_S_cingul-Mid-Post_area',
                 'lh_G_cingul-Post-dorsal_area',
                 'lh_G_cingul-Post-ventral_area',	'lh_G_cuneus_area',
                 'lh_G_front_inf-Opercular_area',	'lh_G_front_inf-Orbital_area',
                 'lh_G_front_inf-Triangul_area', 'lh_G_front_middle_area',
                 'lh_G_front_sup_area',	'lh_G_Ins_lg_and_S_cent_ins_area',
                 'lh_G_insular_short_area',	'lh_G_occipital_middle_area',
                 'lh_G_occipital_sup_area',	'lh_G_oc-temp_lat-fusifor_area',
                 'lh_G_oc-temp_med-Lingual_area',
                 'lh_G_oc-temp_med-Parahip_area',	'lh_G_orbital_area',
                 'lh_G_pariet_inf-Angular_area', 
                 'lh_G_pariet_inf-Supramar_area', 'lh_G_parietal_sup_area',	
                 'lh_G_postcentral_area', 'lh_G_precentral_area',
                 'lh_G_precuneus_area',	'lh_G_rectus_area', 
                 'lh_G_subcallosal_area',	'lh_G_temp_sup-G_T_transv_area',
                 'lh_G_temp_sup-Lateral_area', 'lh_G_temp_sup-Plan_polar_area',
                 'lh_G_temp_sup-Plan_tempo_area',	'lh_G_temporal_inf_area',
                 'lh_G_temporal_middle_area',	'lh_Lat_Fis-ant-Horizont_area',
                 'lh_Lat_Fis-ant-Vertical_area',	'lh_Lat_Fis-post_area',
                 'lh_Pole_occipital_area',	'lh_Pole_temporal_area',
                 'lh_S_calcarine_area',	'lh_S_central_area',
                 'lh_S_cingul-Marginalis_area', 'lh_S_circular_insula_ant_area',
                 'lh_S_circular_insula_inf_area',
                 'lh_S_circular_insula_sup_area', 'lh_S_collat_transv_ant_area',
                 'lh_S_collat_transv_post_area', 'lh_S_front_inf_area',
                 'lh_S_front_middle_area', 'lh_S_front_sup_area',
                 'lh_S_interm_prim-Jensen_area', 
                 'lh_S_intrapariet_and_P_trans_area',
                 'lh_S_oc_middle_and_Lunatus_area',
                 'lh_S_oc_sup_and_transversal_area',	
                 'lh_S_occipital_ant_area',	'lh_S_oc-temp_lat_area',
                 'lh_S_oc-temp_med_and_Lingual_area',
                 'lh_S_orbital_lateral_area',	'lh_S_orbital_med-olfact_area',
                 'lh_S_orbital-H_Shaped_area', 'lh_S_parieto_occipital_area', 
                 'lh_S_pericallosal_area', 'lh_S_postcentral_area', 
                 'lh_S_precentral-inf-part_area', 
                 'lh_S_precentral-sup-part_area',	'lh_S_suborbital_area',
                 'lh_S_subparietal_area',	'lh_S_temporal_inf_area',
                 'lh_S_temporal_sup_area',	'lh_S_temporal_transverse_area')
# All brain variables
brain <- c(all_of(omnibus), all_of(subcortical), all_of(desikanCT), 
           all_of(desikanCA), all_of(destrieuxCT), all_of(destrieuxCA))
brain.region <- list(omnibus = omnibus, 
                     subcortical = subcortical, 
                     desikanCT = desikanCT, 
                     desikanCA = desikanCA, 
                     desikan = c(desikanCT, desikanCA),
                     destrieuxCT = destrieuxCT,
                     destrieuxCA = destrieuxCA,
                     destrieux = c(destrieuxCT, destrieuxCA))
####################
## Create tibbles ##                                                    
####################
  data <- 
  read_csv('RESTRICTED_owensmax_2_8_2021_13_31_28.csv') %>%
  select(c(Subject, Family_ID, Age_in_Yrs)) %>% 
  left_join(
    read_delim('rh_aparc2009_ct_table.txt',","), 
    by = 'Subject') %>%
  left_join(
    read_delim('rh_aparc2009_area_table.txt',","), 
    by = 'Subject') %>%
  left_join(
    read_delim('lh_aparc2009_area_table.txt',","), 
    by = 'Subject') %>%
  left_join(
    read_delim('lh_aparc2009_ct_table.txt',","), 
    by = 'Subject') %>%
  left_join(
    read_csv('/home/max/Documents/hilo/unrestricted_owensmax_2_2_2021_13_58_55.csv') %>% 
      select(c(Subject, Gender, all_of(neo_raw), all_of(subcortical), 
               all_of(desikanCT), all_of(desikanCA), FS_BrainSeg_Vol, 
               FS_Total_GM_Vol, FS_Tot_WM_Vol, FS_TotCort_GM_Vol,
               FS_SubCort_GM_Vol)), 
    by = 'Subject') %>%  
  
  
  drop_na() %>%
  # Create omnibus vars
  mutate(FS_Total_Vol = FS_Total_GM_Vol + FS_Tot_WM_Vol,
         WhiteSurfArea_area = rh_WhiteSurfArea_area + lh_WhiteSurfArea_area,
         MeanThickness_thickness = (rh_MeanThickness_thickness + 
                                      lh_MeanThickness_thickness) / 2) %>%
  # Convert NEO-FFI into numerics. mutate_at() is superseded and this should be 
  # rewritten with across()
  mutate_at(.vars = vars(all_of(neo_raw)), 
            .funs = recode,
            'SD' = 1,
            'D' = 2,
            'N' = 3,
            'A' = 4, 
            'SA' = 5) %>%
  # Create reverse coded items - Items 6, 11, 21, 26, 36, 41, 51,
  # and 56 are reversed in order to create reverse N trait for 
  # calculation of Stability meta trait mutate_at() is superseded and this 
  # should be rewritten with across()
  mutate_at(.vars = vars(c('NEORAW_01', 'NEORAW_03', 'NEORAW_06', 'NEORAW_08',
                           'NEORAW_09', 'NEORAW_11', 'NEORAW_12', 'NEORAW_14',
                           'NEORAW_15', 'NEORAW_16', 'NEORAW_18', 'NEORAW_21',
                           'NEORAW_23', 'NEORAW_24', 'NEORAW_26', 'NEORAW_27',
                           'NEORAW_29', 'NEORAW_30', 'NEORAW_31', 'NEORAW_36',
                           'NEORAW_38', 'NEORAW_39', 'NEORAW_41', 'NEORAW_42',
                           'NEORAW_44', 'NEORAW_45', 'NEORAW_46', 'NEORAW_48',
                           'NEORAW_51', 'NEORAW_54', 'NEORAW_55', 'NEORAW_56',
                           'NEORAW_57', 'NEORAW_59')),
            .funs = list('R' = recode),
            '1' = 5,
            '2' = 4,
            '3' = 3,
            '4' = 2,
            '5' = 1) %>%
  # Create mean trait scores
  mutate(neoN = rowMeans(select(., c(NEORAW_01_R, NEORAW_06, NEORAW_11,
                                     NEORAW_16_R, NEORAW_21, NEORAW_26, 
                                     NEORAW_31_R, NEORAW_36, NEORAW_41, 
                                     NEORAW_46_R, NEORAW_51, NEORAW_56))),
         neoN_R = rowMeans(select(., c(NEORAW_01, NEORAW_06_R, NEORAW_11_R,
                                       NEORAW_16, NEORAW_21_R, NEORAW_26_R,
                                       NEORAW_31, NEORAW_36_R, NEORAW_41_R,
                                       NEORAW_46, NEORAW_51_R, NEORAW_56_R))),
         neoE = rowMeans(select(., c(NEORAW_02, NEORAW_07, NEORAW_12_R,
                                     NEORAW_17, NEORAW_22, NEORAW_27_R, 
                                     NEORAW_32, NEORAW_37, NEORAW_42_R,
                                     NEORAW_47, NEORAW_52, NEORAW_57_R))),
         neoO = rowMeans(select(., c(NEORAW_03_R, NEORAW_08_R, NEORAW_13, 
                                     NEORAW_18_R, NEORAW_23_R, NEORAW_28, 
                                     NEORAW_33, NEORAW_38_R, NEORAW_43, 
                                     NEORAW_48_R, NEORAW_53, NEORAW_58))),
         neoA = rowMeans(select(., c(NEORAW_04, NEORAW_09_R, NEORAW_14_R, 
                                     NEORAW_19, NEORAW_24_R, NEORAW_29_R, 
                                     NEORAW_34, NEORAW_39_R, NEORAW_44_R,
                                     NEORAW_49, NEORAW_54_R, NEORAW_59_R))),
         neoC = rowMeans(select(., c(NEORAW_05, NEORAW_10, NEORAW_15_R,
                                     NEORAW_20, NEORAW_25, NEORAW_30_R,
                                     NEORAW_35, NEORAW_40, NEORAW_45_R, 
                                     NEORAW_50, NEORAW_55_R, NEORAW_60)))) %>%
  # Create facet scores
  mutate(neoAnxiety = rowMeans(select(., c(NEORAW_01_R, NEORAW_21,
                                           NEORAW_31_R))),
         neoDepression = rowMeans(select(., c(NEORAW_16_R, NEORAW_26, NEORAW_41,
                                              NEORAW_46_R))),
         neoSelfConsciousness = rowMeans(select(., c(NEORAW_06, NEORAW_56))),
         neoVulnerability = rowMeans(select(., c(NEORAW_11, NEORAW_51))),
         neoGregariousness = rowMeans(select(., c(NEORAW_02, NEORAW_27_R))),
         neoActivityLevel = rowMeans(select(., c(NEORAW_32, NEORAW_47, 
                                                 NEORAW_52))),
         neoCheerfulness = rowMeans(select(., c(NEORAW_07, NEORAW_12_R, 
                                                NEORAW_37, NEORAW_42_R))),
         neoArtisticInterests = rowMeans(select(., c(NEORAW_03_R, NEORAW_13,
                                                     NEORAW_23_R, NEORAW_43))),
         neoAdventurousness = rowMeans(select(., c(NEORAW_08_R, NEORAW_28))),
         neoIntellect = rowMeans(select(., c(NEORAW_48_R, NEORAW_53, 
                                             NEORAW_58))),
         neoLiberalism = rowMeans(select(., c(NEORAW_18_R, NEORAW_38_R))),
         neoTrust = rowMeans(select(., c(NEORAW_24_R, NEORAW_29_R))),
         neoAltruism = rowMeans(select(., c(NEORAW_04, NEORAW_14_R, NEORAW_34, 
                                            NEORAW_39_R, NEORAW_49))),
         neoCooperation = rowMeans(select(., c(NEORAW_09_R, NEORAW_19,
                                               NEORAW_54_R))),
         neoOrderliness = rowMeans(select(., c(NEORAW_05, NEORAW_15_R,
                                               NEORAW_55_R))),   
         neoDutifulness = rowMeans(select(., c(NEORAW_20, NEORAW_40, 
                                               NEORAW_45_R))),
         neoAchievementStriving = rowMeans(select(., c(NEORAW_25, NEORAW_35, 
                                                       NEORAW_60))),
         neoSelfDiscipline = rowMeans(select(., c(NEORAW_10, NEORAW_30_R, 
                                                  NEORAW_50)))) %>%
  # Standardize domain scores
  mutate(neoN_z = scale(neoN, center = TRUE, scale = TRUE),
         neoN_R_z = scale(neoN_R, center = TRUE, scale = TRUE),
         neoE_z = scale(neoE, center = TRUE, scale = TRUE),
         neoO_z = scale(neoO, center = TRUE, scale = TRUE),
         neoA_z = scale(neoA, center = TRUE, scale = TRUE),
         neoC_z = scale(neoC, center = TRUE, scale = TRUE)) %>%
  # Create metatrait scores
  mutate(neoStability = (neoA_z + neoC_z + neoN_R_z) / 3,
         neoPlasticity = (neoE_z + neoO_z) / 2,
         Gender = recode(Gender,
                         'F' = 0,
                         'M' = 1))
write_csv(data, 'data.csv') 

data_wCog <- data %>% 
  left_join(read_csv('unrestricted_owensmax_2_2_2021_13_58_55.csv') %>% 
              select(c(Subject, CogTotalComp_AgeAdj)), by = 'Subject') %>%
  drop_na()
write_csv(data_wCog, 'data_wCog.csv')

data_wEduc <- data %>% 
  left_join(read_csv('RESTRICTED_owensmax_2_8_2021_13_31_28.csv') %>%
              select(c(Subject, SSAGA_Educ)), by = 'Subject') %>%
  drop_na()
write_csv(data_wEduc, 'data_wEduc.csv')
